import inventory from './nationwide-state-source-discovery.json';

export const DOCUMENT_PROGRAMS = {
  LIHTC: 'LIHTC / Section 42', HOME: 'HOME rental housing', HOME_TBRA: 'HOME tenant-based rental assistance',
  HTF: 'National Housing Trust Fund', HUD_MF: 'HUD Multifamily — PBRA / 202 / 811',
  PUBLIC_HOUSING: 'Public housing', HCV: 'Housing Choice Vouchers', PBV: 'Project-Based Vouchers',
  USDA: 'USDA Rural Development — 515 / 514 / 516 / 521', BOND: 'Tax-exempt bond restrictions',
} as const;
export type DocumentProgram = keyof typeof DOCUMENT_PROGRAMS;
export type DocumentRequirement = {id: string; title: string; applies: readonly DocumentProgram[]; timing: string; category: 'Core file' | 'Conditional' | 'Property / agency record'; detail: string; source: string};
const all = Object.keys(DOCUMENT_PROGRAMS) as DocumentProgram[];
const HUD='https://www.hud.gov/program_offices/administration/hudclips/handbooks/hsgh';
const HCV='https://www.hud.gov/helping-americans/housing-choice-vouchers-guidebook';
const HOME='https://www.ecfr.gov/current/title-24/subtitle-A/part-92';
const HTF='https://www.ecfr.gov/current/title-24/subtitle-A/part-93';
const LIHTC='https://www.irs.gov/pub/irs-pdf/p5913.pdf';
const USDA='https://www.rd.usda.gov/resources/directives/handbooks';
const VAWA='https://www.hud.gov/hud-partners/fair-housing-vawa';
export const DOCUMENT_REQUIREMENTS: readonly DocumentRequirement[] = [
 {id:'application',title:'Application and household composition',applies:all,timing:'Admission; update changes',category:'Core file',detail:'Dated application, household roster, unit and certification dates; record changes and the applicable selection decision.',source:HUD},
 {id:'income',title:'Income declarations and supporting verification',applies:all,timing:'Admission / required reexamination',category:'Core file',detail:'Document every applicable income source using the program’s permitted verification method: employment/pay records, benefits, self-employment records, support, pensions, unemployment and other income. Keep calculation worksheets and discrepancy resolution.',source:HUD},
 {id:'assets',title:'Assets and asset-income documentation',applies:all,timing:'Admission / required reexamination',category:'Core file',detail:'Document applicable accounts, investments, real estate, trusts and disposed assets. Use self-certification only where current program rules permit it; do not require the same bank-statement count for every program.',source:HUD},
 {id:'lease',title:'Executed lease and required addenda',applies:all,timing:'Admission / lease changes',category:'Core file',detail:'Keep the signed lease, required program addenda and applicable notices. A certification does not replace the lease.',source:HCV},
 {id:'limits',title:'Income limit, rent limit and utility allowance evidence',applies:all,timing:'Each applicable determination',category:'Core file',detail:'Retain the correct effective-year schedule, geography, household/unit size, designation and utility method. Source worksheet values are not independently verified limit authority.',source:LIHTC},
 {id:'signatures',title:'Signed certification and effective-date record',applies:all,timing:'Each certification event',category:'Core file',detail:'Use the applicable agency form and required signatories. Retain correction history and notices. A typed OCR proposal is not an executed signature.',source:HUD},
 {id:'zero-income',title:'Zero-income explanation / permitted declaration',applies:all,timing:'When zero income is reported',category:'Conditional',detail:'Document how living expenses are met and use the agency’s required verification or declaration. Not a mandatory form for households with income.',source:HUD},
 {id:'students',title:'Student status and exception evidence',applies:all,timing:'When program student rules apply',category:'Conditional',detail:'Apply the specific program’s student eligibility rules. Preserve enrollment status and evidence for the exception actually claimed; LIHTC and HUD student rules differ.',source:LIHTC},
 {id:'deductions',title:'Deduction / hardship / accommodation evidence',applies:['HUD_MF','PUBLIC_HOUSING','HCV','PBV','HOME','HOME_TBRA','USDA'],timing:'Only if claimed and allowed',category:'Conditional',detail:'Document applicable dependent, childcare, health/medical, disability-assistance or hardship deductions and reasonable accommodations. Do not apply HUD adjusted-income deductions to a LIHTC-only TIC.',source:HUD},
 {id:'identity',title:'Identity, SSN and citizenship / eligible status evidence',applies:['HUD_MF','PUBLIC_HOUSING','HCV','PBV','USDA'],timing:'Admission / relevant household changes',category:'Conditional',detail:'Use each program’s eligibility and disclosure rules, exceptions and age requirements. Do not impose HUD citizenship restrictions on LIHTC-only or HOME-only households.',source:HCV},
 {id:'special',title:'Special occupancy / preference / set-aside evidence',applies:all,timing:'When a restriction or preference applies',category:'Conditional',detail:'Document age, disability, farm-labor eligibility, referral, homelessness, preference, custody or other applicable restriction using permitted evidence. Collect only what the program requires.',source:HUD},
 {id:'changes',title:'Interim change, transfer and recertification notices',applies:all,timing:'When the event occurs',category:'Conditional',detail:'Keep change reports, verification, effective-date calculation, notices and required approvals. Do not demand a new admission packet for every annual or interim event.',source:HCV},
 {id:'lihtc-tic',title:'State-approved TIC and LIHTC student certification',applies:['LIHTC'],timing:'Initial; annual when required',category:'Core file',detail:'Use allocating-agency forms and current compliance instructions. Verify whether an income-recertification exemption applies to a 100% low-income project; state agreements and layered funding may still require annual information.',source:LIHTC},
 {id:'lihtc-property',title:'LIHTC allocation, elections and recorded restrictions',applies:['LIHTC'],timing:'Property record',category:'Property / agency record',detail:'Keep Form 8609/elections, extended-use agreement, applicable set-asides, average-income designations if used, approved rents and utility allowances. These are property records, not forms every tenant completes.',source:LIHTC},
 {id:'home-cert',title:'HOME income determination and unit designation',applies:['HOME'],timing:'Initial and annual under the PJ’s method',category:'Core file',detail:'Retain accepted income evidence/determination, required recertification, HOME unit status, applicable High/Low HOME rent and lease protections. Confirm the participating jurisdiction’s method and periodic full-documentation schedule.',source:HOME},
 {id:'home-tbra',title:'HOME TBRA eligibility and assistance calculation',applies:['HOME_TBRA'],timing:'Admission / renewal',category:'Core file',detail:'Keep income determination, tenant selection, assistance contract, rent reasonableness, subsidy/security-deposit calculations, lease and required inspection evidence under the PJ’s written program.',source:HOME},
 {id:'home-property',title:'HOME written agreement and compliance instructions',applies:['HOME','HOME_TBRA'],timing:'Property / PJ record',category:'Property / agency record',detail:'Identify the actual participating jurisdiction, affordability period, designated units, approved forms, rent/utility method and inspection requirements. The PJ may be a city or county rather than the state HFA.',source:HOME},
 {id:'htf-cert',title:'HTF income certification and eligibility evidence',applies:['HTF'],timing:'Initial and annual',category:'Core file',detail:'Document the grantee’s income method, applicable ELI/VLI category, unit designation, HTF rent/utility limit, lease and annual recertification requirements.',source:HTF},
 {id:'htf-property',title:'HTF written agreement and grantee requirements',applies:['HTF'],timing:'Property / grantee record',category:'Property / agency record',detail:'Keep affordability restrictions, state/grantee monitoring instructions, applicable forms and inspection documentation.',source:HTF},
 {id:'50059',title:'HUD-50059 / applicable HUD-50059-A transaction',applies:['HUD_MF'],timing:'Applicable certification / transaction',category:'Core file',detail:'Retain the signed certification or transaction form, rent computation and required TRACS submission/correction records. Select the correct form for the event.',source:HUD},
 {id:'9887',title:'HUD-9887 / HUD-9887-A consent package',applies:['HUD_MF'],timing:'As required by current consent rules',category:'Core file',detail:'Maintain valid consent for applicable adult members and any additional verification authorizations. Check current form revisions and consent duration instead of assuming every consent is renewed annually.',source:HUD},
 {id:'eiv-mf',title:'Applicable EIV reports and discrepancy resolution',applies:['HUD_MF'],timing:'At program-prescribed events',category:'Core file',detail:'Authorized users retain required EIV identity/income reports and resolve discrepancies under current HUD guidance. EIV is not a requirement for LIHTC-only files.',source:HUD},
 {id:'50058',title:'HUD-50058 family report and rent calculation',applies:['PUBLIC_HOUSING','HCV','PBV'],timing:'Admission / reexamination / reportable changes',category:'Core file',detail:'Keep the applicable family report, calculation evidence and submission/correction record. The signed family declarations and consents are separate documents.',source:HCV},
 {id:'9886',title:'HUD-9886-A and applicable PHA verification records',applies:['PUBLIC_HOUSING','HCV','PBV'],timing:'Admission / required member changes',category:'Core file',detail:'Use valid adult-member consents and the PHA verification hierarchy, EIV checks and discrepancy resolution. Do not automatically require a new 9886-A at every annual reexamination.',source:'https://www.hud.gov/sites/dfiles/OCHCO/documents/2024-38pihn.pdf'},
 {id:'ph-lease',title:'Public housing lease, rent option and inspection record',applies:['PUBLIC_HOUSING'],timing:'Admission / applicable review',category:'Core file',detail:'Keep PHA lease/addenda, income-based or flat-rent determination as applicable, required inspections and eligibility evidence under the ACOP. Community-service exemption/compliance evidence applies only where required.',source:'https://www.ecfr.gov/current/title-24/subtitle-B/chapter-IX/part-960'},
 {id:'hcv-lease',title:'Voucher, RFTA, lease, tenancy addendum and HAP',applies:['HCV'],timing:'Voucher issuance / initial lease / move',category:'Core file',detail:'Include HUD-52646, HUD-52517, applicable HUD-52641 and tenancy addendum, approved rent reasonableness, payment-standard/utility calculation, required inspection and applicable HUD-52675. Some records belong to the PHA or owner, not the tenant.',source:HCV},
 {id:'pbv-lease',title:'PBV eligibility, lease/addendum and assistance records',applies:['PBV'],timing:'Admission / leasing / changes',category:'Core file',detail:'Use PBV-specific forms, PHA eligibility and rent records, the executed tenant lease/addendum and applicable inspection evidence. The project HAP/AHAP is maintained at project/PHA level; do not substitute a tenant-based voucher HAP.',source:'https://www.ecfr.gov/current/title-24/subtitle-B/chapter-IX/part-983'},
 {id:'pha-policy',title:'Local PHA Administrative Plan / ACOP and special overlays',applies:['PUBLIC_HOUSING','HCV','PBV'],timing:'Agency record',category:'Property / agency record',detail:'Select the actual PHA. Document MTW, RAD, VASH, FUP, EHV or other special-program conditions where applicable. A state-wide library alone does not establish a local PHA’s requirements.',source:HCV},
 {id:'rd-cert',title:'RD 3560-8 tenant certification and calculations',applies:['USDA'],timing:'Initial / annual / interim as required',category:'Core file',detail:'Use the RD form version applicable to the effective date; include household signatures, verified eligibility/adjusted income, assets and tenant-rent/rental-assistance calculations.',source:USDA},
 {id:'rd-file',title:'RD lease, eligibility and required addenda',applies:['USDA'],timing:'Admission / relevant changes',category:'Core file',detail:'Keep the approved lease, applicable rental-assistance and farm-labor eligibility evidence, occupancy/selection records and verification required by HB-2-3560 Chapter 6.',source:USDA},
 {id:'bond',title:'Bond regulatory agreement and issuer certification',applies:['BOND'],timing:'Admission / issuer-required recertification',category:'Core file',detail:'Use the issuer’s regulatory agreement, income restrictions, required certification and supporting income evidence. Apply LIHTC requirements separately when credits are also present.',source:'https://www.irs.gov/tax-exempt-bonds'},
 {id:'vawa-distribution',title:'VAWA notice and certification form distribution',applies:all,timing:'Covered program / required notice events',category:'Conditional',detail:'Provide HUD-5380 and HUD-5382, or applicable agency-approved equivalents, at required events and retain required delivery evidence. A completed survivor statement is not a routine requirement for every certification.',source:VAWA},
 {id:'vawa-case',title:'VAWA documentation / emergency-transfer request',applies:all,timing:'Only when protections or transfer are requested',category:'Conditional',detail:'HUD-5382 or permitted alternative documentation, and HUD-5383 where applicable. Keep survivor information confidential and out of shared databases; a police report is not universally required.',source:VAWA},
 {id:'vawa-plan',title:'VAWA emergency-transfer plan and applicable lease addendum',applies:all,timing:'Covered provider / program record',category:'Property / agency record',detail:'HUD-5381 is a model provider plan, not a form every tenant completes. Retain the adopted plan and required program-specific lease addendum, including HUD-91067 where applicable.',source:VAWA},
 {id:'lead',title:'Lead-based paint disclosure and related notices',applies:all,timing:'Covered pre-1978 housing / required events',category:'Conditional',detail:'Include disclosure, pamphlet, known reports and required acknowledgments where lead rules apply; exemptions and additional assisted-housing requirements must be checked.',source:'https://www.hud.gov/program_offices/healthy_homes/enforcement/disclosure'},
 {id:'state-overlay',title:'State, local and property-specific forms / approvals',applies:all,timing:'Before treating the file as complete',category:'Property / agency record',detail:'Reconcile the selected state’s agency forms, local funding restrictions, regulatory agreements, current limits and utility schedules, certification event and effective-date rules. Resolve every applicable missing item or document why it is not applicable.',source:HUD},
];

const stateNames='AL:Alabama|AK:Alaska|AZ:Arizona|AR:Arkansas|CA:California|CO:Colorado|CT:Connecticut|DE:Delaware|DC:District of Columbia|FL:Florida|GA:Georgia|HI:Hawaii|ID:Idaho|IL:Illinois|IN:Indiana|IA:Iowa|KS:Kansas|KY:Kentucky|LA:Louisiana|ME:Maine|MD:Maryland|MA:Massachusetts|MI:Michigan|MN:Minnesota|MS:Mississippi|MO:Missouri|MT:Montana|NE:Nebraska|NV:Nevada|NH:New Hampshire|NJ:New Jersey|NM:New Mexico|NY:New York|NC:North Carolina|ND:North Dakota|OH:Ohio|OK:Oklahoma|OR:Oregon|PA:Pennsylvania|RI:Rhode Island|SC:South Carolina|SD:South Dakota|TN:Tennessee|TX:Texas|UT:Utah|VT:Vermont|VA:Virginia|WA:Washington|WV:West Virginia|WI:Wisconsin|WY:Wyoming';
export const STATE_DOCUMENT_LIBRARIES=stateNames.split('|').map(entry=>{
 const [code,name]=entry.split(':');
 return {code:code!,name:name!,agencies:inventory.jurisdictions.filter(j=>j.state_code===code).map(j=>({name:j.agency,scope:j.scope,sources:j.sources})), requirements:DOCUMENT_REQUIREMENTS};
}).sort((a,b)=>a.name.localeCompare(b.name));
export const LIBRARY_REVIEW_DATE='2026-09-08';
export function documentChecklist(programs: readonly DocumentProgram[]){return DOCUMENT_REQUIREMENTS.filter(d=>programs.some(p=>d.applies.includes(p)));}
