project_id = "emnkzxkcpnyvglwxraxm"

[functions.operations-worker]
verify_jwt = false

[functions.merlin-procedure-worker]
verify_jwt = false

[functions.income-calculator]
verify_jwt = false

[functions.support-notification-worker]
verify_jwt = false
