import { calculateTicWorksheet } from '@/lib/tic-calculations';
import { TicIncomeWorksheet } from '@/components/tic-income-worksheet';
import { useMemo } from 'react';
import { FREQUENCIES } from '../../supabase/functions/_shared/income-calculator-engine';
import { calculateIncomePreparation, type IncomeDraft, type IncomePage, type IncomeRow } from '@/lib/certification-income-evidence';

type Props = { value: IncomeDraft; pages: IncomePage[]; sourceUrl: string | null; busy: boolean; onChange: (draft: IncomeDraft) => void; onContinue: () => void; onBack: () => void };
const control = 'mt-1 w-full rounded border bg-background px-3 py-2 text-sm';
const money = (v: string | null) => v === null ? 'Needs information' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(v));

export function CertificationIncomeCalculator({ value, pages, sourceUrl, busy, onChange, onContinue, onBack }: Props) {
  const result = useMemo(() => {try{return calculateIncomePreparation(value,pages);}catch(error){return {annualIncome:null,rows:[],issues:[error instanceof Error?error.message:'Correct the worksheet inputs.']};}},[value,pages]);
  const ticView=useMemo(()=>{if(!value.ticWorksheet)return null;try{return calculateTicWorksheet(value.ticWorksheet.values,value.ticWorksheet.settings);}catch(error){return {...calculateTicWorksheet(value.ticWorksheet.values),issues:[error instanceof Error?error.message:'Correct worksheet settings.']};}},[value.ticWorksheet]);
  const change = (patch: Partial<IncomeDraft>) => onChange({ ...value, ...patch, confirmed: false });
  const row = (id: string, patch: Partial<IncomeRow>) => change({ rows: value.rows.map(r => r.id === id ? { ...r, ...patch } : r) });
  const field = (r: IncomeRow, title: string, name: keyof IncomeRow, type = 'text') => <label className="block text-xs font-medium">{title}<input aria-label={`${title} · ${r.id}`} className={control} type={type} inputMode={name === 'amount' || name === 'weeks' ? 'decimal' : undefined} value={String(r[name])} maxLength={1000} disabled={busy} onChange={e => row(r.id, { [name]: e.target.value })} /></label>;
  return <section aria-label="Certification Income Calculator" className="mt-4 space-y-4 rounded-xl border bg-background p-4">
    <div><h3 className="text-lg font-semibold">3. Income Calculator</h3><p className="mt-2 text-sm text-muted-foreground">Income amounts recovered from selected documents appear below. Complete any missing details. CertivoIQ calculates annual income automatically as you work.</p><p className="mt-2 text-xs text-muted-foreground">This is a projected income worksheet. Program rules, exclusions, asset treatment and eligibility are checked during the full certification review.</p></div>
    <label className="block max-w-sm text-sm font-medium">Certification effective date<input aria-label="Income certification effective date" type="date" className={control} value={value.effectiveDate} disabled={busy} onChange={e => change({ effectiveDate: e.target.value })} /></label>
    {value.ticWorksheet && <><label className="block text-sm">Calculation source<select aria-label="Income calculation source" className={control} disabled={busy} value={value.basis||'EVIDENCE'} onChange={e=>change({basis:e.target.value as 'TIC'|'EVIDENCE'})}><option value="TIC">TIC annual income and assets</option><option value="EVIDENCE">Paystubs and other supporting income evidence</option></select></label>{value.basis==='TIC'&&ticView&&<TicIncomeWorksheet worksheet={ticView} settings={value.ticWorksheet.settings} busy={busy} onSettings={settings=>change({ticWorksheet:{...value.ticWorksheet!,settings}})}/>}</>}
    {!pages.length && <p role="alert" className="rounded border p-3 text-sm">Select Pay Stub / Check Stub, Employment Verification, Bank Statement, Other Income, or Certification of Zero Income for the relevant uploaded pages.</p>}
    {value.basis!=='TIC' && value.rows.map((r, index) => <article key={r.id} className="space-y-3 rounded-lg border p-4">
      <div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">Income evidence {index + 1} · original page {r.page}</strong>{sourceUrl && <a href={`${sourceUrl}#page=${r.page}`} target="_blank" rel="noreferrer" className="text-sm underline">View source page {r.page}</a>}</div>
      <details className="text-xs"><summary className="cursor-pointer">Show extracted source text</summary><pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap">{pages.find(p => p.page === r.page)?.excerpt || 'No readable text recovered. Compare the source image.'}</pre></details>
      <label className="block text-xs font-medium">How this evidence is used<select aria-label={`Income evidence type · ${r.id}`} className={control} value={r.kind} disabled={busy} onChange={e => row(r.id, { kind: e.target.value as IncomeRow['kind'] })}><option value="wages">Gross wages — average comparable pay periods</option><option value="other">Other Income — benefits, support, self-employment and other sources</option><option value="asset">Asset income — interest or other supported asset earnings</option><option value="exclude">Do not count — explain below</option></select></label>
      {r.kind !== 'exclude' && <><div className="grid gap-3 sm:grid-cols-2">{field(r, 'Household member', 'member')}{field(r, 'Employer / income source', 'sourceName')}{field(r, r.kind === 'wages' ? 'Current gross pay ($)' : 'Supported income amount ($)', 'amount')}<label className="block text-xs font-medium">Payment frequency<select aria-label={`Payment frequency · ${r.id}`} className={control} value={r.frequency} disabled={busy} onChange={e => row(r.id, { frequency: e.target.value as IncomeRow['frequency'] })}><option value="">Confirm frequency</option>{Object.keys(FREQUENCIES).map(f => <option key={f} value={f}>{({ WEEKLY: 'Weekly · 52', BIWEEKLY: 'Every two weeks · 26', SEMIMONTHLY: 'Twice monthly · 24', MONTHLY: 'Monthly · 12', ANNUAL: 'Annual · 1' })[f as keyof typeof FREQUENCIES]}</option>)}</select></label>{field(r, 'Evidence period start', 'periodStart', 'date')}{field(r, 'Evidence period end', 'periodEnd', 'date')}{r.kind === 'wages' && <>{field(r, 'Expected paid weeks in coming year', 'weeks')}{field(r, 'Net annual expected-change adjustment ($)', 'annualAdjustment')}</>}</div>{r.kind === 'wages' && <p className="text-xs text-muted-foreground">Use the same member and employer for paystubs from the same job. Comparable complete periods are averaged once. The initial 52 paid weeks assumes a full year; adjust seasonal work. Enter bonuses and known changes as a documented net annual adjustment, consistently on each stub from the same job.</p>}</>}
      {field(r, r.kind === 'exclude' ? 'Reason this evidence is not counted' : 'Source notes / known changes', 'note')}
      <div className="flex flex-wrap gap-3 text-xs"><button type="button" disabled={busy} className="underline" onClick={() => change({ rows: [...value.rows, { ...r, id: crypto.randomUUID(), member: '', sourceName: '', amount: '', note: '', kind: 'other' }] })}>Add another income source on page {r.page}</button>{value.rows.filter(x => x.page === r.page).length > 1 && <button type="button" disabled={busy} className="underline" onClick={() => change({ rows: value.rows.filter(x => x.id !== r.id) })}>Remove this added row</button>}</div>
    </article>)}
    {pages.some(p => p.type === 'zero_income_certification') && <label className="flex items-start gap-2 text-sm"><input type="checkbox" checked={value.zeroIncome} disabled={busy} onChange={e => change({ zeroIncome: e.target.checked })} />The included zero-income evidence supports no income for this household. I have explained each excluded row.</label>}
    <div className="rounded-lg border bg-muted/30 p-4" aria-live="polite"><h4 className="font-semibold">Calculated projected annual income: {money(result.annualIncome)}</h4><p className="mt-1 text-xs">Pending full certification review</p>{result.rows.map((r, i) => <p key={`${r.id}-${i}`} className="mt-2 text-sm">{r.basis}{r.annual !== null ? ` = ${money(r.annual)}` : ''}</p>)}{result.issues.length > 0 && <ul className="mt-3 list-disc space-y-1 pl-5 text-sm">{result.issues.map(i => <li key={i}>{i}</li>)}</ul>}</div>
    <label className="flex items-start gap-2 text-sm"><input aria-label="Confirm income evidence" type="checkbox" disabled={busy || result.annualIncome === null} checked={value.confirmed} onChange={e => onChange({ ...value, confirmed: e.target.checked })} />{value.basis==='TIC'?'I checked the entered TIC income, asset amounts, passbook rate and selected method. These figures remain subject to supporting-evidence and program review.':'I checked the recovered income amounts, complete comparable pay periods, payment frequencies, expected paid weeks and known changes. Every income source is represented, and duplicates and principal are not counted twice.'}</label>
    <div className="flex flex-wrap justify-between gap-3"><button type="button" disabled={busy} className="rounded border px-4 py-2 text-sm" onClick={onBack}>Back to TIC</button><button type="button" disabled={busy || !value.confirmed || result.annualIncome === null} className="rounded bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50" onClick={onContinue}>Add calculated income & prepare full review</button></div>
  </section>;
}
