import { useQuery } from "@tanstack/react-query";
import { AppShell } from "@/components/app-shell";
import { Panel, Pill, Stat } from "@/components/ui-kit";
import { useWorkspaceProfile } from "@/hooks/use-workspace-profile";
import { supabase } from "@/integrations/supabase/client";

type ControlRow={program_code:string;source_release_status:string;rule_version_status:string;hotma_policy_status:string;reporting_path_status:string;software_compatibility_status:string;source_status_conflict:boolean;source_authority_key:string|null;rule_version:string|null;validated_at:string|null};
type Counts={familyBlocked:number;txBlocked:number;policyValidated:number;policyTotal:number};
const PROGRAM_LABELS:Record<string,string>={hcv:"HCV",pbv:"PBV",public_housing:"Public Housing",mod_rehab:"Mod Rehab"};
function tone(ok:boolean){return ok?"seal" as const:undefined;}
export function PhaHotmaReadinessWorkspace(){
 const {profile,workspaceUserId}=useWorkspaceProfile();
 const controls=useQuery<ControlRow[]>({queryKey:["pha-hotma-controls",workspaceUserId],enabled:!!workspaceUserId,queryFn:async()=>{ // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const client=supabase as any; const {data,error}=await client.from("pha_authoritative_control_state").select("program_code,source_release_status,rule_version_status,hotma_policy_status,reporting_path_status,software_compatibility_status,source_status_conflict,source_authority_key,rule_version,validated_at").eq("user_id",workspaceUserId); if(error) throw error; return data??[]; }});
 const counts=useQuery<Counts>({queryKey:["pha-hotma-readiness-counts",workspaceUserId],enabled:!!workspaceUserId,queryFn:async()=>{ // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const client=supabase as any; const [fa,tx,pol]=await Promise.all([client.from("pha_family_actions").select("id",{count:"exact",head:true}).eq("user_id",workspaceUserId).or("controlled_source_release_approved.eq.false,current_rule_version_validated.eq.false,source_status_conflict.eq.true,full_hotma_policy_set_validated.eq.false,reporting_path_validated.eq.false,software_compatibility_validated.eq.false"),client.from("pha_50058_transactions").select("id",{count:"exact",head:true}).eq("user_id",workspaceUserId).in("routing_status",["BLOCKED","AWAITING_HUD_GUIDANCE"]),client.from("pha_notice_policy_overlays").select("validated").eq("workspace_user_id",workspaceUserId).eq("active",true)]); if(fa.error)throw fa.error;if(tx.error)throw tx.error;if(pol.error)throw pol.error;const policies=pol.data??[];return{familyBlocked:fa.count??0,txBlocked:tx.count??0,policyValidated:policies.filter((p:{validated:boolean})=>p.validated).length,policyTotal:policies.length};}});
 const rows=controls.data??[]; const c=counts.data??{familyBlocked:0,txBlocked:0,policyValidated:0,policyTotal:0};
 const cohortReady=Boolean(profile.pha_hotma_cohort&&profile.hud_50058_reporting_path); const standardDeadline=profile.pha_hotma_cohort==="NON_MTW_NON_FRS"?"January 1, 2027":"HUD guidance pending";
 const fullyReady=profile.pha_programs.length>0&&profile.pha_programs.every(program=>{const r=rows.find(x=>x.program_code===program);return !!r&&r.source_release_status==="approved"&&r.rule_version_status==="current"&&["validated","not_applicable"].includes(r.hotma_policy_status)&&r.reporting_path_status==="validated"&&r.software_compatibility_status==="validated"&&!r.source_status_conflict;})&&cohortReady;
 return <AppShell title="PHA HOTMA Readiness" subtitle="Live program, policy, source, reporting-path, software and transaction readiness for HOTMA implementation">
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Stat label="Overall readiness" value={fullyReady?"Ready":"Action required"} hint="All enrolled programs must pass every control"/><Stat label="Implementation cohort" value={profile.pha_hotma_cohort?.replaceAll("_"," ")??"Not configured"} hint={`Enforcement route: ${standardDeadline}`}/><Stat label="Blocked family actions" value={c.familyBlocked} hint="Derived control failures in active workflow"/><Stat label="HUD-50058 exceptions" value={c.txBlocked} hint="Blocked or awaiting HUD guidance"/><Stat label="Validated policies" value={`${c.policyValidated}/${c.policyTotal}`} hint="Active Admin Plan / ACOP / program policy overlays"/></div>
  <Panel className="mt-4" title="Program control matrix" description="These values come from the staff-governed authoritative control state. Agency users can view but cannot alter the underlying control record."><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="pb-3">Program</th><th className="pb-3">Sources</th><th className="pb-3">Rule version</th><th className="pb-3">HOTMA policy</th><th className="pb-3">50058 path</th><th className="pb-3">Software</th><th className="pb-3">Conflict</th><th className="pb-3">Authority</th></tr></thead><tbody>{profile.pha_programs.map(program=>{const r=rows.find(x=>x.program_code===program);return <tr key={program} className="border-t border-border"><td className="py-3 pr-3 font-medium">{PROGRAM_LABELS[program]??program}</td><td className="py-3 pr-3"><Pill tone={tone(r?.source_release_status==="approved")}>{r?.source_release_status??"missing"}</Pill></td><td className="py-3 pr-3"><Pill tone={tone(r?.rule_version_status==="current")}>{r?.rule_version_status??"missing"}</Pill></td><td className="py-3 pr-3"><Pill tone={tone(["validated","not_applicable"].includes(r?.hotma_policy_status??""))}>{r?.hotma_policy_status??"missing"}</Pill></td><td className="py-3 pr-3"><Pill tone={tone(r?.reporting_path_status==="validated")}>{r?.reporting_path_status??"missing"}</Pill></td><td className="py-3 pr-3"><Pill tone={tone(r?.software_compatibility_status==="validated")}>{r?.software_compatibility_status??"missing"}</Pill></td><td className="py-3 pr-3"><Pill tone={tone(r?.source_status_conflict===false)}>{r?.source_status_conflict?"conflict":"clear"}</Pill></td><td className="py-3 text-xs text-muted-foreground">{r?.source_authority_key??"No controlled authority"}{r?.rule_version?` · ${r.rule_version}`:""}</td></tr>})}{profile.pha_programs.length===0?<tr className="border-t border-border"><td colSpan={8} className="py-8 text-center text-muted-foreground">No PHA programs are configured.</td></tr>:null}</tbody></table></div></Panel>
  <div className="mt-4 grid gap-4 lg:grid-cols-2"><Panel title="Applicability" description="HOTMA is derived from the agency's enrolled programs; it is not a user-selectable program."><div className="space-y-2 text-sm"><div className="flex justify-between rounded-md border border-border p-3"><span>Sections 102 / 104</span><Pill tone="seal">Covered PHA programs</Pill></div><div className="flex justify-between rounded-md border border-border p-3"><span>Section 103 over-income</span><Pill tone={tone(profile.pha_programs.includes("public_housing"))}>{profile.pha_programs.includes("public_housing")?"Public Housing applicable":"Not applicable"}</Pill></div><div className="flex justify-between rounded-md border border-border p-3"><span>HUD-50058 reporting path</span><Pill tone={tone(Boolean(profile.hud_50058_reporting_path))}>{profile.hud_50058_reporting_path??"Not configured"}</Pill></div></div></Panel><Panel title="Release logic" description="CertivoIQ does not mark an agency ready from a deadline alone."><p className="text-sm leading-6 text-muted-foreground">Each enrolled program must have approved controlled sources, a current rule version, validated HOTMA policy state, validated reporting path, compatible software, and no source conflict. MTW and FRS-exclusive cohorts remain blocked from inheriting the non-MTW January 1, 2027 enforcement assumption until applicable HUD guidance is controlled.</p></Panel></div>
 </AppShell>;
}
