import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Panel, Pill, Stat } from "@/components/ui-kit";
import { supabase } from "@/integrations/supabase/client";

type RequestRow = { id:string; requester_reference:string; program_code:string; request_context:string; requested_accommodation:string; status:string; effective_communication_required:boolean; communication_format:string|null; decision_reason:string|null; alternative_accommodation:string|null; requested_at:string };
const inputClass="mt-1 w-full rounded-md border border-border bg-background px-3 py-2 text-sm";
export function PhaReasonableAccommodationWorkspace(){
 const qc=useQueryClient(); const [draft,setDraft]=useState({requester_reference:"",program_code:"hcv",request_context:"communication",requested_accommodation:"",effective_communication_required:false,communication_format:""});
 const q=useQuery<RequestRow[]>({queryKey:["pha-ra"],queryFn:async()=>{ // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const client=supabase as any; const {data,error}=await client.from("pha_reasonable_accommodation_requests").select("id,requester_reference,program_code,request_context,requested_accommodation,status,effective_communication_required,communication_format,decision_reason,alternative_accommodation,requested_at").order("requested_at",{ascending:false}); if(error) throw error; return data??[]; }});
 const create=useMutation({mutationFn:async()=>{if(!draft.requester_reference.trim()||!draft.requested_accommodation.trim()) throw new Error("Requester reference and requested accommodation are required."); // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const client=supabase as any; const {error}=await client.from("pha_reasonable_accommodation_requests").insert({...draft,requester_reference:draft.requester_reference.trim(),requested_accommodation:draft.requested_accommodation.trim(),communication_format:draft.communication_format.trim()||null}); if(error) throw error;},onSuccess:async()=>{setDraft({requester_reference:"",program_code:"hcv",request_context:"communication",requested_accommodation:"",effective_communication_required:false,communication_format:""}); await qc.invalidateQueries({queryKey:["pha-ra"]});}});
 const rows=q.data??[]; return <AppShell title="Reasonable Accommodations" subtitle="Track accommodation requests across applications, waiting lists, inspections, reexams, hearings, and communications">
  <div className="grid gap-3 md:grid-cols-3"><Stat label="Open requests" value={rows.filter(r=>["received","interactive_process"].includes(r.status)).length} hint="Protected from automatic adverse action"/><Stat label="Approved" value={rows.filter(r=>r.status.startsWith("approved")).length} hint="Approved or approved alternative"/><Stat label="Effective communication" value={rows.filter(r=>r.effective_communication_required).length} hint="Accessible communication required"/></div>
  <div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel title="Record request" description="Requests can affect multiple PHA workflows and must be evaluated case by case."><form className="space-y-3" onSubmit={e=>{e.preventDefault();create.mutate();}}><label className="block text-xs font-medium">Requester / case reference<input className={inputClass} value={draft.requester_reference} onChange={e=>setDraft(v=>({...v,requester_reference:e.target.value}))}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Program<select className={inputClass} value={draft.program_code} onChange={e=>setDraft(v=>({...v,program_code:e.target.value}))}><option value="hcv">HCV</option><option value="pbv">PBV</option><option value="public_housing">Public Housing</option><option value="mod_rehab">Mod Rehab</option></select></label><label className="text-xs font-medium">Context<select className={inputClass} value={draft.request_context} onChange={e=>setDraft(v=>({...v,request_context:e.target.value}))}>{["application","waiting_list","eligibility","briefing","inspection","leasing","reexamination","termination","hearing","communication","other"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label></div><label className="block text-xs font-medium">Requested accommodation<textarea className={`${inputClass} min-h-24`} value={draft.requested_accommodation} onChange={e=>setDraft(v=>({...v,requested_accommodation:e.target.value}))}/></label><label className="flex items-center gap-2 text-xs font-medium"><input type="checkbox" checked={draft.effective_communication_required} onChange={e=>setDraft(v=>({...v,effective_communication_required:e.target.checked}))}/>Effective communication required</label>{draft.effective_communication_required?<label className="block text-xs font-medium">Communication format<input className={inputClass} value={draft.communication_format} onChange={e=>setDraft(v=>({...v,communication_format:e.target.value}))} placeholder="ASL interpreter, large print, accessible electronic format…"/></label>:null}<button className="rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground" disabled={create.isPending}>Record request</button>{create.isError?<p className="text-xs text-destructive">{create.error instanceof Error?create.error.message:"Unable to record request."}</p>:null}</form></Panel>
  <Panel title="Control standard" description="A request may be made at any time. CertivoIQ prevents a waiting-list removal while an associated accommodation review is open."><div className="space-y-3 text-sm text-muted-foreground"><p>Decisions are case specific. A denial must state the reason.</p><p>If the requested accommodation would create an undue financial/administrative burden or fundamental alteration, an effective alternative must still be considered.</p><p>Effective communication requirements are tracked independently so notices, briefings, hearings, and digital communications can be delivered accessibly.</p></div></Panel></div>
  <Panel className="mt-4" title="Accommodation register"><div className="overflow-x-auto"><table className="w-full min-w-[860px] text-left text-sm"><thead className="text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="pb-3">Requester</th><th className="pb-3">Program</th><th className="pb-3">Context</th><th className="pb-3">Request</th><th className="pb-3">Status</th><th className="pb-3">Communication</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-border"><td className="py-3 pr-3 font-medium">{r.requester_reference}</td><td className="py-3 pr-3">{r.program_code.replaceAll("_"," ").toUpperCase()}</td><td className="py-3 pr-3">{r.request_context.replaceAll("_"," ")}</td><td className="py-3 pr-3 max-w-md truncate">{r.requested_accommodation}</td><td className="py-3 pr-3"><Pill tone={r.status.startsWith("approved")?"seal":undefined}>{r.status.replaceAll("_"," ")}</Pill></td><td className="py-3 text-xs">{r.effective_communication_required?(r.communication_format??"required"):"standard"}</td></tr>)}</tbody></table></div></Panel>
 </AppShell>;
}
