import type { TicWorksheet, TicWorksheetSettings } from '@/lib/tic-calculations';
const labels:Record<string,string>={total_income_e:'Total Income (E)',total_asset_cash_value:'Total asset cash value',total_income_assets_m:'Total Asset Income (M)',household_annual_income:'Total annual household income',worksheet_total_actual_income:'Actual asset income',worksheet_total_imputed_income:'Imputed asset income',gross_rent:'Gross rent',current_income_limit_140_percent:'Income limit × 140%'};
export function TicIncomeWorksheet({worksheet,settings,onSettings,busy,trial=false}:{worksheet:TicWorksheet;settings:TicWorksheetSettings;onSettings:(s:TicWorksheetSettings)=>void;busy:boolean;trial?:boolean}){
 const change=(key:keyof TicWorksheetSettings,value:string)=>onSettings({...settings,[key]:value});
 const selectPolicy=(hotmaStatus:NonNullable<TicWorksheetSettings['hotmaStatus']>)=>{
  if(hotmaStatus==='HOTMA_2026')onSettings({...settings,hotmaStatus,passbookRatePercent:'0.40',assetMethod:'HOTMA_PER_ASSET',imputationThreshold:'52787',rateSource:'HUD CY 2026 passbook rate · effective January 1, 2026'});
  else if(hotmaStatus==='PRE_HOTMA_AUTHORIZED')onSettings({...settings,hotmaStatus,passbookRatePercent:'0.06',assetMethod:'LEGACY_GREATER',imputationThreshold:'5000',rateSource:'Authorized pre-HOTMA HUD Multifamily / agency policy'});
  else onSettings({...settings,hotmaStatus,passbookRatePercent:'',assetMethod:'SOURCE',imputationThreshold:'',rateSource:hotmaStatus==='AGENCY_SPECIFIC'?'Enter the controlling agency or property policy source':''});
 };
 return <section className="my-4 space-y-3 rounded-lg border bg-background p-4" aria-label="Calculated TIC income worksheet">
 <h3 className="font-semibold">Calculated TIC income worksheet</h3><p className="text-sm">Totals update from the entered TIC amounts. Check the source values before continuing.</p>
 {trial&&<div className="rounded-lg border border-primary/20 bg-primary/5 p-3"><p className="text-sm font-semibold">Free-review program settings</p><p className="mt-1 text-xs text-muted-foreground">Choose the program and implementation status used for this certification. The selection is saved with this review.</p><div className="mt-3 grid gap-3 sm:grid-cols-2">
 <label className="text-sm">Program<select aria-label="Certification program for passbook rate" className="mt-1 w-full rounded border bg-background p-2" value={settings.programContext||''} disabled={busy} onChange={e=>change('programContext',e.target.value)}><option value="">Select program</option><option value="HUD_MFH">HUD Multifamily / PBRA</option><option value="HCV_PH">Housing Choice Voucher / Public Housing</option><option value="HOME_HTF">HOME / HTF</option><option value="LIHTC">LIHTC</option><option value="USDA_RD">USDA Rural Development</option><option value="OTHER">Other / property-specific</option></select></label>
 <label className="text-sm">HOTMA / governing policy status<select aria-label="HOTMA status for passbook rate" className="mt-1 w-full rounded border bg-background p-2" value={settings.hotmaStatus||''} disabled={busy} onChange={e=>selectPolicy(e.target.value as NonNullable<TicWorksheetSettings['hotmaStatus']>)}><option value="">Select status</option><option value="HOTMA_2026">HOTMA implemented — 2026 HUD rate</option><option value="PRE_HOTMA_AUTHORIZED">Authorized pre-HOTMA policy</option><option value="AGENCY_SPECIFIC">Agency/property-specific — enter manually</option></select></label>
 </div>{settings.hotmaStatus==='HOTMA_2026'&&<p className="mt-2 text-xs font-medium">Applied: 0.40% passbook rate and $52,787 2026 imputation threshold.</p>}{settings.hotmaStatus==='PRE_HOTMA_AUTHORIZED'&&<p className="mt-2 text-xs font-medium">Applied: 0.06% passbook rate and $5,000 legacy threshold. Confirm the property or agency is authorized to use this policy.</p>}{settings.hotmaStatus==='AGENCY_SPECIFIC'&&<p className="mt-2 text-xs text-flag">Enter the documented rate, asset method, threshold, and source below.</p>}</div>}
 <div className="grid gap-3 sm:grid-cols-2">
 <label className="text-sm">Passbook rate (%) — this review only<input aria-label="Passbook rate percent" inputMode="decimal" className="mt-1 w-full rounded border bg-background p-2" value={settings.passbookRatePercent} disabled={busy} onChange={e=>change('passbookRatePercent',e.target.value)}/><span className="block text-xs text-muted-foreground">Enter 0.06 for 0.06%. Editing this rate does not change other reviews or a program's published rate.</span></label>
 <label className="text-sm">Asset-income calculation<select aria-label="Asset income calculation method" className="mt-1 w-full rounded border bg-background p-2" value={settings.assetMethod} disabled={busy} onChange={e=>change('assetMethod',e.target.value)}><option value="SOURCE">Use the total reported on the TIC</option><option value="ACTUAL">Actual asset income only</option><option value="LEGACY_GREATER">Legacy — greater of actual or imputed</option><option value="HOTMA_PER_ASSET">HOTMA — actual plus eligible imputed assets</option></select></label>
 <label className="text-sm">Applicable imputation threshold ($)<input aria-label="Imputation threshold" inputMode="decimal" className="mt-1 w-full rounded border bg-background p-2" value={settings.imputationThreshold} disabled={busy} onChange={e=>change('imputationThreshold',e.target.value)}/></label>
 <label className="text-sm">Rate / method source or explanation<input aria-label="Passbook rate source" className="mt-1 w-full rounded border bg-background p-2" value={settings.rateSource} disabled={busy} onChange={e=>change('rateSource',e.target.value)}/></label>
 </div>
 {(settings.assetMethod==='SOURCE'||settings.assetMethod==='ACTUAL')&&<p className="text-sm text-muted-foreground">The selected method does not apply a passbook rate. To calculate imputed asset income, select the applicable imputation method and enter its threshold.</p>}
 <div className="overflow-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Income sources from the TIC</caption><thead><tr><th>Member</th><th>Annual income source</th><th>Amount</th></tr></thead><tbody>{worksheet.incomeRows.map((r,i)=><tr key={i}><td>{r.member}</td><td>{r.source}</td><td>{r.annual}</td></tr>)}</tbody></table></div>
 <dl className="grid gap-2 sm:grid-cols-2">{Object.entries(labels).map(([field,label])=><div key={field}><dt className="text-xs">{label}</dt><dd className="font-semibold">{worksheet.values[field]||'Needs information'}</dd></div>)}</dl>
 {worksheet.issues.length>0&&<ul className="list-disc pl-5 text-sm">{worksheet.issues.map(i=><li key={i}>{i}</li>)}</ul>}
 {worksheet.differences.length>0&&<details><summary className="cursor-pointer font-medium">Differences from source figures ({worksheet.differences.length})</summary><ul className="list-disc pl-5 text-sm">{worksheet.differences.map(d=><li key={d.field}>{labels[d.field]||d.field.replaceAll('_',' ')}: source {d.reported}; calculated {d.calculated}.</li>)}</ul></details>}
 <p className="text-xs text-muted-foreground">A trial rate adjustment is a review input. Full review must verify the applicable property/program limits, income exclusions and eligibility; changing this rate does not establish qualification.</p>
 </section>;
}

