import type { TicWorksheet, TicWorksheetSettings } from '@/lib/tic-calculations';
const labels:Record<string,string>={total_income_e:'Total Income (E)',total_asset_cash_value:'Total asset cash value',total_income_assets_m:'Total Asset Income (M)',household_annual_income:'Total annual household income',worksheet_total_actual_income:'Actual asset income',worksheet_total_imputed_income:'Imputed asset income',gross_rent:'Gross rent',current_income_limit_140_percent:'Income limit × 140%'};
export function TicIncomeWorksheet({worksheet,settings,onSettings,busy}:{worksheet:TicWorksheet;settings:TicWorksheetSettings;onSettings:(s:TicWorksheetSettings)=>void;busy:boolean}){
 const change=(key:keyof TicWorksheetSettings,value:string)=>onSettings({...settings,[key]:value});
 return <section className="my-4 space-y-3 rounded-lg border bg-background p-4" aria-label="Calculated TIC income worksheet">
 <h3 className="font-semibold">Calculated TIC income worksheet</h3><p className="text-sm">Totals update from the entered TIC amounts. Check the source values before continuing.</p>
 <div className="grid gap-3 sm:grid-cols-2">
 <label className="text-sm">Passbook rate (%) — this review only<input aria-label="Passbook rate percent" inputMode="decimal" className="mt-1 w-full rounded border bg-background p-2" value={settings.passbookRatePercent} disabled={busy} onChange={e=>change('passbookRatePercent',e.target.value)}/><span className="block text-xs text-muted-foreground">Enter 0.06 for 0.06%. Editing this rate does not change other reviews or a program's published rate.</span></label>
 <label className="text-sm">Asset-income calculation<select aria-label="Asset income calculation method" className="mt-1 w-full rounded border bg-background p-2" value={settings.assetMethod} disabled={busy} onChange={e=>change('assetMethod',e.target.value)}><option value="SOURCE">Use the total reported on the TIC</option><option value="ACTUAL">Actual asset income only</option><option value="LEGACY_GREATER">Legacy — greater of actual or imputed</option><option value="HOTMA_PER_ASSET">HOTMA — actual plus eligible imputed assets</option></select></label>
 <label className="text-sm">Applicable imputation threshold ($)<input aria-label="Imputation threshold" inputMode="decimal" className="mt-1 w-full rounded border bg-background p-2" value={settings.imputationThreshold} disabled={busy} onChange={e=>change('imputationThreshold',e.target.value)}/></label>
 <label className="text-sm">Rate / method source or explanation<input aria-label="Passbook rate source" className="mt-1 w-full rounded border bg-background p-2" value={settings.rateSource} disabled={busy} onChange={e=>change('rateSource',e.target.value)}/></label>
 </div>
 <div className="overflow-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Income sources from the TIC</caption><thead><tr><th>Member</th><th>Annual income source</th><th>Amount</th></tr></thead><tbody>{worksheet.incomeRows.map((r,i)=><tr key={i}><td>{r.member}</td><td>{r.source}</td><td>{r.annual}</td></tr>)}</tbody></table></div>
 <dl className="grid gap-2 sm:grid-cols-2">{Object.entries(labels).map(([field,label])=><div key={field}><dt className="text-xs">{label}</dt><dd className="font-semibold">{worksheet.values[field]||'Needs information'}</dd></div>)}</dl>
 {worksheet.issues.length>0&&<ul className="list-disc pl-5 text-sm">{worksheet.issues.map(i=><li key={i}>{i}</li>)}</ul>}
 {worksheet.differences.length>0&&<details><summary className="cursor-pointer font-medium">Differences from source figures ({worksheet.differences.length})</summary><ul className="list-disc pl-5 text-sm">{worksheet.differences.map(d=><li key={d.field}>{labels[d.field]||d.field.replaceAll('_',' ')}: source {d.reported}; calculated {d.calculated}.</li>)}</ul></details>}
 <p className="text-xs text-muted-foreground">A trial rate adjustment is a review input. Applicable property/program authority, income exclusions, and eligibility are evaluated during the full certification review.</p>
 </section>;
}
