/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as LaunchpadRouteImport } from './routes/launchpad'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as TrialRouteImport } from './routes/trial'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademyCourseIdRouteImport } from './routes/academy.$courseId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as FilesIndexRouteImport } from './routes/files.index'
import { Route as FilesFileIdRouteImport } from './routes/files.$fileId'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchpadRoute = LaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialRoute = TrialRouteImport.update({
  id: '/trial',
  path: '/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyCourseIdRoute = AcademyCourseIdRouteImport.update({
  id: '/academy/$courseId',
  path: '/academy/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesFileIdRoute = FilesFileIdRouteImport.update({
  id: '/files/$fileId',
  path: '/files/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/findings': typeof FindingsRoute
  '/launchpad': typeof LaunchpadRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/trial': typeof TrialRoute
  '/welcome': typeof WelcomeRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/academy/$courseId': typeof AcademyCourseIdRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/academy/': typeof AcademyIndexRoute
  '/files/': typeof FilesIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/findings': typeof FindingsRoute
  '/launchpad': typeof LaunchpadRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/trial': typeof TrialRoute
  '/welcome': typeof WelcomeRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/academy/$courseId': typeof AcademyCourseIdRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/academy': typeof AcademyIndexRoute
  '/files': typeof FilesIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/copilot': typeof CopilotRoute
  '/findings': typeof FindingsRoute
  '/launchpad': typeof LaunchpadRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rules': typeof RulesRoute
  '/trial': typeof TrialRoute
  '/welcome': typeof WelcomeRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/academy/$courseId': typeof AcademyCourseIdRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/files/$fileId': typeof FilesFileIdRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/academy/': typeof AcademyIndexRoute
  '/files/': typeof FilesIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/copilot'
    | '/findings'
    | '/launchpad'
    | '/pricing'
    | '/reset-password'
    | '/rules'
    | '/trial'
    | '/welcome'
    | '/billing'
    | '/crm'
    | '/security'
    | '/academy/$courseId'
    | '/api/chat'
    | '/checkout/return'
    | '/files/$fileId'
    | '/properties/$propertyId'
    | '/academy/'
    | '/files/'
    | '/properties/'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/copilot'
    | '/findings'
    | '/launchpad'
    | '/pricing'
    | '/reset-password'
    | '/rules'
    | '/trial'
    | '/welcome'
    | '/billing'
    | '/crm'
    | '/security'
    | '/academy/$courseId'
    | '/api/chat'
    | '/checkout/return'
    | '/files/$fileId'
    | '/properties/$propertyId'
    | '/academy'
    | '/files'
    | '/properties'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/copilot'
    | '/findings'
    | '/launchpad'
    | '/pricing'
    | '/reset-password'
    | '/rules'
    | '/trial'
    | '/welcome'
    | '/_authenticated/billing'
    | '/_authenticated/crm'
    | '/_authenticated/security'
    | '/academy/$courseId'
    | '/api/chat'
    | '/checkout/return'
    | '/files/$fileId'
    | '/properties/$propertyId'
    | '/academy/'
    | '/files/'
    | '/properties/'
    | '/api/public/payments/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CopilotRoute: typeof CopilotRoute
  FindingsRoute: typeof FindingsRoute
  LaunchpadRoute: typeof LaunchpadRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RulesRoute: typeof RulesRoute
  TrialRoute: typeof TrialRoute
  WelcomeRoute: typeof WelcomeRoute
  AcademyCourseIdRoute: typeof AcademyCourseIdRoute
  ApiChatRoute: typeof ApiChatRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  FilesFileIdRoute: typeof FilesFileIdRoute
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  FilesIndexRoute: typeof FilesIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launchpad': {
      id: '/launchpad'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof LaunchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial': {
      id: '/trial'
      path: '/trial'
      fullPath: '/trial'
      preLoaderRoute: typeof TrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$courseId': {
      id: '/academy/$courseId'
      path: '/academy/$courseId'
      fullPath: '/academy/$courseId'
      preLoaderRoute: typeof AcademyCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$fileId': {
      id: '/files/$fileId'
      path: '/files/$fileId'
      fullPath: '/files/$fileId'
      preLoaderRoute: typeof FilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CopilotRoute: CopilotRoute,
  FindingsRoute: FindingsRoute,
  LaunchpadRoute: LaunchpadRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RulesRoute: RulesRoute,
  TrialRoute: TrialRoute,
  WelcomeRoute: WelcomeRoute,
  AcademyCourseIdRoute: AcademyCourseIdRoute,
  ApiChatRoute: ApiChatRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  FilesFileIdRoute: FilesFileIdRoute,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  FilesIndexRoute: FilesIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
